apps:
  - script: ./gateway-hue-review
    name: "gateway-hue-review"
    instances: 1
    env:
      PORT: 4000
  - script: ./service-accounts
    name: "service-accounts"
    instances: 1
    env:
      PORT: 4001
  - script: ./service-colors
    name: "service-colors"
    instances: 1
    env:
      PORT: 4002
  - script: ./service-reviews
    name: "service-reviews"
    instances: 1
    env:
      PORT: 4003